Use "git worktree" instead of "git stash" and "git checkout"
WillAbides/benchdiff pull request #12
Opened 2021-03-31 12:10 UTC by FiloSottile

Thank you for building this!

This PR switches `runAtGitRef` to using the fantastic `git worktree` command, which creates a new working directory from the current repository, without the overhead of a fresh clone. It has several advantages over `git stash` + `git checkout`: it doesn't modify files in the current working directory, avoiding invalidating builds and confusing editors; it protects from accidental modifications during the benchmark; and guarantees a fresh checkout without untracked files which might modify the behavior of the program.

2021-04-01 21:28 UTC, WillAbides commented
Thanks for this PR.  I thought there was a way to do this with worktree, but I never quite got it working. This should be a lot cleaner.
 
All of the go parts of this PR look good, and from what I can tell the git is good too. I would like to spend a couple of days using this fork locally before merging.  I happen to be doing a lot of benchmarking this week, so I will have plenty of opportunity.

2021-04-04 20:20 UTC, WillAbides requested changes
This made a huge difference when using benchdiff this week. I didn't realize how much I had become used to the editor reload issues when running this. Not having to deal with that is great.

I requested a few small changes. Once those are done it's ready to merge and release.

2021-04-04 20:20 UTC, WillAbides commented on cmd/benchdiff/internal/gitrunner.go
> +	worktree, err := ioutil.TempDir("", "bindiff")
```suggestion
	worktree, err := ioutil.TempDir("", "benchdiff")
```

2021-04-04 20:20 UTC, WillAbides commented on cmd/benchdiff/internal/gitrunner.go
> +	defer os.RemoveAll(worktree)
So they know what can be cleaned up manually if something goes wrong.

```suggestion
	defer func() {
		rErr := os.RemoveAll(worktree)
		if rErr != nil {
			fmt.Printf("Could not delete temp directory: %s\n", worktree)
		}
	}()
```

2021-04-04 20:20 UTC, WillAbides commented on cmd/benchdiff/internal/gitrunner_test.go
>  		got, err = ioutil.ReadFile(fooPath)
To avoid the shadowed variable.

```suggestion
		wdFooPath := filepath.Join(workDir, "foo")
		got, err = ioutil.ReadFile(wdFooPath)
```

2021-04-04 20:20 UTC, WillAbides commented on cmd/benchdiff/internal/testutil_test.go
> -func tmpDir(t *testing.T) string {
Thanks for modernizing this while you were at it.

2021-04-06 01:38 UTC, FiloSottile commented
All done! Thank you!

2021-04-06 14:08 UTC, merged

2021-04-06 14:15 UTC, WillAbides commented
This is released in v0.7.0.  Thanks again for this contribution.